My 7nd Homework
lshchurko/lshchurko3 pull request #7
Opened 2022-03-22 14:47 UTC by lshchurko

Разработать классы для программы управления ИТ офисом.
1. Класс Office содержит список Employee, сотрудники бывают QAEmployee, DevEmployee, BAEmployee, PMEmployee, QAAutomationEmployee, QAAutomationTeamLead, DevTEamLead, QATeamLead.
2. Ассайнить таски могут тимлиды и PMEmployee, делать ревью кода тимлиды QAAutomation и Dev.
3. Писать код могут Dev, QAAuto и их тимлиды.
4. Заполнить список Employee специалистами разного профиля, и вывести подробную информацию о специлистах, которые могут
4.1 писать код
4.2 ассайнить таски
4.3 делать ревью кода

2022-03-30 15:53 UTC, EgorAntonovich requested changes

2022-03-30 15:53 UTC, EgorAntonovich commented on itOffice_homework7/itOffice_homework7/Office.cs
> +        List<Employee> _employees;
private

2022-03-30 15:53 UTC, EgorAntonovich commented on itOffice_homework7/itOffice_homework7/Program.cs
> +            foreach (Employee employee in ls.Employees)
Simplify in 1 foreach

2022-04-07 07:33 UTC, lshchurko commented on itOffice_homework7/itOffice_homework7/Office.cs
> +        List<Employee> _employees;
Changed

2022-04-07 07:34 UTC, lshchurko commented on itOffice_homework7/itOffice_homework7/Program.cs
> +            foreach (Employee employee in ls.Employees)
Changed

2022-04-12 19:20 UTC, EgorAntonovich approved these changes

2022-04-12 19:20 UTC, merged